name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-on-linux:
    name: compile on linux Ubuntu
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependency
        run: |
          sudo apt-get install libatlas-base-dev libfftw3-dev libplplot-dev
      - name: Build on Linux Ubuntu
        run: |
          ./autogen.sh
          ./configure
          make -j

  build-on-mac:
    name: compile on MacOS
    continue-on-error: false
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependency
        run: |
          brew install automake
          brew install openblas
          brew install lapack
          brew install atlas
          brew install fftw
          brew install plplot
      - name: Build on MacOS
        run: |
          export LDFLAGS="-L/usr/local/opt/lapack/lib -L/usr/local/opt/openblas/lib"
          export CPPFLAGS="-I/usr/local/opt/lapack/include -L/usr/local/opt/openblas/lib"
          export PKG_CONFIG_PATH="/usr/local/opt/lapack/lib/pkgconfig:/usr/local/opt/openblas/lib/pkgconfig"
          ./autogen.sh
          ./configure --enable-openblas
          make -j

